name: hello_flutter
description: A new Flutter module.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/test_scale.jpg
    - assets/test_scale2.jpg
  module:
    androidX: true
    androidPackage: com.zhaopf.hello_flutter
    iosBundleIdentifier: com.zhaopf.helloFlutter
